import sys; sys.path.insert(0, "/tmp/cat")
from engine import build, render
def B(a, **k): return dict({"ar": a, "w": 400, **k})
def S(a, **k): return dict({"ar": a, "w": 700, "r": 196, "maxw": 148, **k})
def L(a, **k): return dict({"ar": a, "w": 600, "r": 196, "maxw": 148, **k})
def V(a, **k): return dict({"ar": a, "w": 400, "anchor": "center", **k})
RL, RR = 281, 536
def T(a, r): return dict(ar=a, w=600, r=r, size=10.5, maxw=218)
def D(a, r): return dict(ar=a, w=400, r=r)
p0 = {
 "Split Phase | Low Voltage": B("طور منقسم | جهد منخفض"),
 "Experience Uninterrupted Power with Solis Energy Storage Inverters": B("طاقة بلا انقطاع مع إنفرترات تخزين الطاقة من Solis"),
 "GINLONG TECHNOLOGIES CO., LTD.": B("شركة GINLONG TECHNOLOGIES المحدودة"),
 "• Supports PV input up to 160% of the inverter's rated": T("• يدعم مدخل PV حتى 160% من القدرة المقننة للإنفرتر", RL),
 "DC power, maximising solar utilisation": D("لطاقة DC، مما يرفع الاستفادة من الطاقة الشمسية", RL - 9),
 "• Supports up to 21A PV input current, compatible with": T("• يدعم تيار دخل PV حتى 21A، ومتوافق مع", RL),
 "future higher-power PV modules": D("ألواح PV المستقبلية ذات القدرات الأعلى", RL - 9),
 "• 200% overload for 10s in off-grid mode, ensuring stable": T("• تحميل زائد 200% لمدة 10s في وضع خارج الشبكة", RL),
 "startup of motors, water pumps and air conditioners": D("لضمان تشغيل مستقر للمحركات والمضخات والمكيفات", RL - 9),
 "• Seamless on/off-grid switching in under 10ms,": T("• تبديل سلس بين وضعي الشبكة وخارجها خلال أقل من 10ms", RL),
 "guaranteeing an uninterrupted power supply": D("مما يضمن إمداداً بالطاقة دون انقطاع", RL - 9),
 "• Support split-phase unbalanced output, each phase": T("• يدعم خرجاً غير متوازن للطور المنقسم، ويمكن لكل طور", RL),
 "supports output max. 50% rated inverter power": D("تقديم حتى 50% من القدرة المقننة للإنفرتر", RL - 9),
 "• More battery options, compatible with any battery": T("• خيارات بطاريات أوسع، متوافق مع أي بطارية", RL),
 "(between 40V-60V)": D("بجهد بين 40V و60V", RL - 9),
 "• Supports existing PV grid-tied power connection for": T("• يدعم ربط منظومة PV القائمة المتصلة بالشبكة", RL),
 "export control and off-grid use": D("للتحكم في التصدير والاستخدام خارج الشبكة", RL - 9),
 "• Multiple methods of generator connection and auto": T("• طرق متعددة لتوصيل المولد والتحكم التلقائي به", RR),
 "control, enabling flexible local deployment": D("مما يتيح تركيباً محلياً مرناً", RR - 10),
 "• Support max 6 units in parallel, for expanding": T("• يدعم ربط حتى 6 وحدات على التوازي", RR),
 "system capacity": D("لتوسيع سعة النظام", RR - 10),
 "• Smart Load management, extending backup time": T("• إدارة ذكية للأحمال تطيل زمن الدعم الاحتياطي", RR),
 "for critical loads": D("للأحمال الحرجة", RR - 10),
 "• Customizable battery backup level for uninterrupted": T("• مستوى احتياطي للبطارية قابل للتخصيص", RR),
 "power": D("لضمان استمرارية الطاقة", RR - 10),
 "• PV only off grid mode, to reduce the initial": T("• وضع خارج الشبكة بالألواح فقط لتقليل", RR),
 "investment cost": D("تكلفة الاستثمار الأولية", RR - 10),
 "• 7-inch industrial-grade touchscreen, providing a": T("• شاشة لمس صناعية مقاس 7 بوصات توفر", RR),
 "larger, user-friendly interface for local operation": D("واجهة أكبر وأسهل للتشغيل المحلي", RR - 10),
 "• Ingress protection IP66, adapting to harsh ambient": T("• درجة حماية IP66 للتكيّف مع الظروف", RR),
 "conditions": D("المحيطة القاسية", RR - 10),
}
p1 = {
 "DATASHEET": B("نشرة المواصفات", w=700),
 "Models": S("الطرازات", maxw=200),
 "Input DC (PV side)": S("دخل DC - جهة الألواح"),
 "Recommended max. PV array size": L("أقصى حجم موصى به لمصفوفة PV"),
 "Max. usable PV input power": L("أقصى قدرة دخل PV قابلة للاستخدام"),
 "Max. input voltage": L("أقصى جهد دخل"),
 "Rated voltage": L("الجهد المقنن"),
 "Start-up voltage": L("جهد بدء التشغيل"),
 "MPPT voltage range": L("نطاق جهد MPPT"),
 "Max. input current": L("أقصى تيار دخل"),
 "Max. short circuit current": L("أقصى تيار قصر"),
 "MPPT number / Max. input strings number": L("عدد MPPT / أقصى عدد سلاسل"),
 "THDi": L("THDi"),
 "Battery": S("البطارية"),
 "Battery type": L("نوع البطارية"),
 "Li-ion / Lead-acid": V("ليثيوم أيون / رصاص حمضي"),
 "Battery voltage range": L("نطاق جهد البطارية"),
 "Max. charge / discharge power": L("أقصى قدرة شحن / تفريغ"),
 "Max. charge / discharge current": L("أقصى تيار شحن / تفريغ"),
 "Communication": L("الاتصال"),
 "Output AC (Grid side)": S("خرج AC - جهة الشبكة"),
 "Rated output power": L("قدرة الخرج المقننة"),
 "Rated grid voltage": L("جهد الشبكة المقنن"),
 "Rated grid frequency": L("تردد الشبكة المقنن"),
 "Rated grid output current": L("تيار الخرج المقنن للشبكة"),
 "Max. output current": L("أقصى تيار خرج"),
 "Power factor": L("معامل القدرة"),
 "> 0.99 (0.8 leading - 0.8 lagging)": V("> 0.99  من 0.8 متقدم إلى 0.8 متأخر"),
 "Input AC (Grid side)": S("دخل AC - جهة الشبكة"),
 "Input voltage range": L("نطاق جهد الدخل"),
 "Frequency range": L("نطاق التردد"),
 "Input Generator": S("دخل المولد"),
 "Max. input power": L("أقصى قدرة دخل"),
 "Rated input frequency": L("تردد الدخل المقنن"),
 "Output AC (Back-up)": S("خرج AC - الاحتياطي"),
 "Max. apparent output power": L("أقصى قدرة خرج ظاهرية"),
 "2 times of rated power, 10 s": V("ضعف القدرة المقننة لمدة 10 s"),
 "Back-up switch time": L("زمن التحويل للاحتياطي"),
 "Rated output voltage": L("جهد الخرج المقنن"),
 "Rated frequency": L("التردد المقنن"),
 "Rated output current": L("تيار الخرج المقنن"),
 "Max. AC passthrough current": L("أقصى تيار AC مار"),
 "THDv (@linear load)": L("THDv عند حمل خطي"),
 "Efficiency": S("الكفاءة"),
 "Max. efficiency": L("أقصى كفاءة"),
 "EU efficiency": L("الكفاءة الأوروبية"),
 "BAT charged by PV / AC max. efficiency": L("أقصى كفاءة شحن البطارية من PV / AC"),
 "BAT discharged to AC max. efficiency": L("أقصى كفاءة تفريغ البطارية إلى AC"),
 "Protection": S("الحماية"),
 "Surge protection": L("الحماية من التدفق المفاجئ"),
 "Ground fault monitoring": L("مراقبة أعطال التأريض"),
 "Integrated AFCI 2.0": L("AFCI 2.0 مدمج"),
 "DC reverse-polarity protection": L("حماية DC من عكس القطبية"),
 "Protection class / Over voltage category": L("فئة الحماية / فئة الجهد الزائد"),
 "I / II (PV and BAT), III (MAINS and BACKUP and GEN)": V("I / II للألواح والبطارية،  III للشبكة والاحتياطي والمولد"),
 "Dados gerais": S("بيانات عامة"),
 "Max. allowable phase imbalance (grid & back-up)": L("أقصى عدم توازن مسموح بين الأطوار"),
 "Dimensions (W × H × D)": L("الأبعاد (W × H × D)"),
 "Weight": L("الوزن"),
 "Topology": L("الطوبولوجيا"),
 "Transformerless": V("بدون محوّل"),
 "Self-consumption (night)": L("الاستهلاك الذاتي ليلاً"),
 "Operating ambient temperature range": L("نطاق حرارة التشغيل المحيطة"),
 "Relative humidity": L("الرطوبة النسبية"),
 "Ingress protection": L("درجة الحماية"),
 "Noise emission (typical)": L("مستوى الضجيج النموذجي"),
 "Cooling concept": L("طريقة التبريد"),
 "Intelligent fan-cooling": V("تبريد ذكي بالمراوح"),
 "Max. operation altitude": L("أقصى ارتفاع للتشغيل"),
 "Grid connection standard": L("معيار الربط بالشبكة"),
 "Safety / EMC standard": L("معايير السلامة والتوافق EMC"),
 "Features": S("المميزات"),
 "DC connection": L("توصيل DC"),
 "MC4 plug (PV port) / Terminal Block (BAT port)": V("قابس MC4 لمنفذ PV  /  أطراف توصيل لمنفذ البطارية"),
 "AC connection": L("توصيل AC"),
 "OT terminal": V("أطراف OT"),
 "Display": L("الشاشة"),
 "7.0\" LCD display & Bluetooth + APP": V("شاشة LCD مقاس 7.0 بوصة + Bluetooth + تطبيق"),
 "Communication interface": L("واجهات الاتصال"),
}
if __name__ == "__main__":
    src, dst = sys.argv[1], sys.argv[2]
    build(src, dst, {0: p0, 1: p1})
    render(dst, dst[:-4])
